151 namespace info
HSLdevcom/hsl-map-publisher-ui pull request #37
Opened 2020-10-15 13:16 UTC by ahjyrkia

2020-10-16 05:17 UTC, Pesonet1 requested changes

2020-10-16 05:17 UTC, Pesonet1 commented on src/components/Login.js
> +const InfoIcon = () => (
Tämän ikonin voisi siirtää omaan tiedostoon.

2020-10-19 10:55 UTC, ahjyrkia commented on src/components/Login.js
> +const InfoIcon = () => (
done

2020-10-19 11:01 UTC, Pesonet1 approved these changes

2020-10-19 12:43 UTC, merged